### PR TITLE
14 bug/fix simulate routing

### LINKED ISSUE #15: Fix simulate routing
- Simulate routing is not working.There are some logical error

### PR DESCRIPTION
**Pull request by Praanim**
- Closes #15

### CODE REVIEW

File: example/lib/map_dashboard_screen.dart [hunk 1]
```diff
@@ -68,60 +76,59 @@ class MapDashboardScreenState extends State<MapDashboardScreen> {
...
 
     directionRouteResponse = await apiRequest.getDrivingRouteUsingGraphHooper(
-      customBaseUrl: '',
-        source: userLocation!.position,
+        // customBaseUrl: 'https://route.naxa.com.np',
+        source: userLocation.position,
         destination: latLng,
         navigationType: NavigationProfile.car,
-    graphHooperApiKey: 'Your GraphHooper API Key');
+        graphHooperApiKey: '9adf4607-bac4-4bae-83be-d29509ce743d');
```
Comment (amias-samir) [inline example/lib/map_dashboard_screen.dart]: remove the token from here!

File: example/lib/map_dashboard_screen.dart [hunk 2]
```diff
@@ -68,60 +76,59 @@ class MapDashboardScreenState extends State<MapDashboardScreen> {
...
+      iconSize: markerSize,
+      iconImage: "assets/icon/health_icon.png",
+    ));
 
     ApiRequest apiRequest = ApiRequest();
 
     directionRouteResponse = await apiRequest.getDrivingRouteUsingGraphHooper(
-      customBaseUrl: '',
-        source: userLocation!.position,
+        // customBaseUrl: 'https://route.naxa.com.np',
```
Comment (amias-samir) [inline example/lib/map_dashboard_screen.dart]: use base URL and token from env/secret file!

File: example/lib/map_dashboard_screen.dart [hunk 3]
```diff
@@ -68,60 +76,59 @@ class MapDashboardScreenState extends State<MapDashboardScreen> {
...
 
     directionRouteResponse = await apiRequest.getDrivingRouteUsingGraphHooper(
-      customBaseUrl: '',
-        source: userLocation!.position,
+        source: userLocation.position,
         destination: latLng,
         navigationType: NavigationProfile.car,
-    graphHooperApiKey: 'Your GraphHooper API Key');
+        graphHooperApiKey:
+            dotenv.env["API_KEY"] ?? "Include your API key in the env file");
```
Comment (Praanim) [inline example/lib/map_dashboard_screen.dart:116]: Done here

**Review by amias-samir — APPROVED** [review]

**Review by amias-samir — APPROVED** [review]

**Review by amias-samir — APPROVED** [review]
